server:
  port: 8080

spring:
  profiles:
    active: test
  application:
    name: resume-builder

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/resume_builder
    username: postgres
    password: 1234qwer

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key: sk-whxgnenapgsuyayocfolxjwbrvxomducfauplezvzimdgbsn
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
          temperature: 0.3
          max-tokens: 8000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

  sql:
    init:
      mode: never

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.resume: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.ai: debug
    org.springframework.web.client: debug
