server:
  port: ${PORT:8080}

spring:
  application:
    name: resume-builder

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resume_builder}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234qwer}

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY:your-api-key-here}
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
          temperature: 0.3
#          max-tokens: 8000

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: false

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.resume: debug
